"""anu

Revision ID: 055ab341f62b
Revises: 
Create Date: 2025-01-29 17:19:53.833619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055ab341f62b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('saran', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_depan', sa.String(length=100), nullable=False),
    sa.Column('nama_belakang', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('conflict_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conflict_id'], ['conflicts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('conflict_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conflict_id'], ['conflicts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riwayat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('masalah', sa.Text(), nullable=False),
    sa.Column('solusi', sa.Text(), nullable=False),
    sa.Column('kepastian', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('conflict_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conflict_id'], ['conflicts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solutions')
    op.drop_table('riwayat')
    op.drop_table('relations')
    op.drop_table('examples')
    op.drop_table('user')
    op.drop_table('conflicts')
    # ### end Alembic commands ###
